name: ${project.name}
main: net.plazmix.essentials.PlazmixEssentialsPlugin
version: ${project.version}
description: ${project.description}
website: ${project.url}

author: Frotter

depend: [PlazmixAPI]
